[package]
name = "collapse-expand-fasta"
version = "0.2.1"
edition = "2021"

[dependencies]
bio = "2.0.3"
serde = { version = "1.0.210"}
clap = { version = "4.5.18", features = ["derive"] }
serde_json = "1.0.128"
log = "0.4.22"
simple_logger = "5.0.0"